name: First time repo setup
run-name: First time repo setup

on:
  push:
    branches: [main]

# only keep latest run of this workflow
concurrency:
  group: template-cleanup
  cancel-in-progress: true

permissions: 
  actions: write
  checks: write
  contents: write

jobs:
  template-cleanup:
    name: Template cleanup
    runs-on: ubuntu-latest

    # Ensure is is only run once, when the repository is generated, with a check to ensure it's the main branch
    if: github.run_number == 1 && github.ref == 'refs/heads/main'

    steps:
      # get main branch repo contents
      - name: Checkout code
        uses: actions/checkout@v4

      # remove files not needed for user instance of template
      - name: Remove workflows
        run: rm -rf .github

      # save changed files
      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Template cleanup"
